#
#  temp.yaml
#  Surmagic
#
#  Created by Muhammed Gurhan Yerlikaya on 28.02.2022.
#  Copyright Â© 2022 https://github.com/gurhub/surmagic.
#

name: Create Release Binary

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  GIT_USER_NAME: "gurhub"
  GIT_USER_EMAIL: "gurhanyerlikaya@gmail.com"

jobs:
  
  # ---------------------------------
  # Create Release Binary
  # ---------------------------------
  create-release-binary:
    runs-on: macos-11
    steps:
       - name: ğŸ›’ Checkout for the Create Release Binary
         uses: actions/checkout@v2

       - run: |
           echo "ğŸ§± Swift Build"
           cd surmagic
           ls -lat
           swift build -c release
           echo "ğŸ— Copy the Binary"
           cp .build/release/surmagic ../bin/
       
       - run: echo "ğŸšš Commit for Create Release Binary"
       - run: git add .
       - run: git status
       - run: git commit -m "Create Release Binary and copy under the /bin directory"
       - run: git status
       - run: git push origin master
